import './globals.css'
import type { Metadata } from 'next'
import { Work_Sans } from 'next/font/google'

const workSans = Work_Sans({
  subsets: ['latin', 'vietnamese'],
})

export const metadata: Metadata = {
  title: 'Shop Cake App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={workSans.className}>{children}</body>
    </html>
  )
}
